version: '2'
services:

  jeecg-cloud-mysql:
    build:
      context: ./doc/db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: jeecg-cloud-mysql
    image: jeecg-cloud-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 3306:3306

  jeecg-cloud-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: jeecg-cloud-redis
    hostname: jeecg-cloud-redis

  jeecg-cloud-rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
    restart: always
    container_name: jeecg-cloud-rabbitmq
    hostname: jeecg-cloud-rabbitmq

  jeecg-cloud-nacos:
    restart: always
    image: nacos/nacos-server
    container_name: jeecg-cloud-nacos
    hostname: jeecg-cloud-nacos
    ports:
      - 8848:8848
    environment:
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: jeecg-cloud-mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: jeecg-nacos
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      MODE: standalone

  